#!/bin/bash

for file in $(find ./{default,openhab,frank} -type f 2>/dev/null); do
    tr -d '\015' <$file >"$file""_new"
    mv "$file""_new" $file
done

git add .
git commit -m "Fix LF"
git push

echo "Done"

