#!/bin/bash

# shellcheck disable=2155

readonly repo_location="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PRETTY_HOSTNAME=""
[[ -r "${HOME}/.pretty_hostname" ]] && PRETTY_HOSTNAME="$(head -n 1 "${HOME}/.pretty_hostname" | tr -d '[:space:]')"
[[ -n ${PRETTY_HOSTNAME} ]] || PRETTY_HOSTNAME="$(hostname -s)"
export PRETTY_HOSTNAME

readonly all_files=$(find "${repo_location}"/AliasesAndFunctions/{default,"$(echo "${PRETTY_HOSTNAME}" | tr '[:upper:]' '[:lower:]')",conditional} -type f 2>/dev/null)

for file in ${all_files}; do
	# shellcheck disable=1090
	source "${file}"
done
