#!/bin/bash

repoLocation="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

while read -r file; do
    # shellcheck disable=1090
    source "${file}"
done < <(find "${repoLocation}"/{default,"$(hostname | tr '[:upper:]' '[:lower:]')"} -type f 2>/dev/null)
