#!/bin/bash

readonly repo_location="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly all_files=$(find "${repo_location}"/AliasesAndFunctions/{default,"$(hostname -s | tr '[:upper:]' '[:lower:]')",conditional} -type f 2>/dev/null)

for file in ${all_files}; do
	# shellcheck disable=1090
	source "${file}"
done
