#!/bin/bash


cd "$( dirname "${BASH_SOURCE[0]}" )" #Move to the script location

git pull 2>/dev/null >/dev/null || echo -e "\e[31m\e[1mEs gab ein Problem beim Updaten des bashrc-Repos!\e[0m" 1>&2

cd - >/dev/null
exit 0
