#!/bin/bash

alias ..="cd .."; alias ,,=".."; alias ...="cd ../.."; alias ....="cd ../../.."; alias .....="cd ../../../.."; alias ......="cd ../../../../.."
alias dc='cd'
alias ls="ls -lh --color=always --time-style='+%H:%M %d.%m.%Y'"; alias l='ls'; alias ll='ls'; alias lll='ls'; alias sl='ls'; alias la="ls -A"
alias rm='rm -R'
alias status='git status'
alias update='sudo apt update && apt list --upgradable'
alias upgradable='apt list --upgradable'
alias mygrep='grep -ins --color=always'
alias nano='nano -l -T 4'
alias less='less -IN'
alias cp='rsync -arh --info=progress2'
alias b='exec $SHELL'
alias pwd='pwd -P' #Den absoluten Pfad angeben und keine Symnlinks verwenden
alias tf='tail -f -n 1000'
alias df="df -h"
alias git="git --no-pager" #Kein Pager für alle git Befehle anzeigen
alias time="stopwatch"
alias ct="cd /tmp/ && git clone git@github.com:Trysupe/testing.git && cd testing/"
alias ip='ip -color'

[[ -n $(command -v code) ]] && alias c='code .'
           [[ -n ${TMUX} ]] && alias help='tmux_help'

export log_auth="/var/log/auth.log"
