#!/bin/bash

alias ..="cd .."
alias ,,=".."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias ls="ls -lh --color=always --time-style='+%H:%M %d.%m.%Y'"
alias l='ls'
alias ll='ls'
alias lll='ls'
alias sl='ls'
alias la="ls -A"

alias upgradable='apt list --upgradable'
alias update='sudo apt update && apt list --upgradable'

alias b='exec ${SHELL} -l' # -l ensures that the bashrc is loaded
alias ct="cd /tmp/; [[ -d testing ]] || git clone git@github.com:Trysupe/testing.git; cd testing/"
alias mygrep='grep -ins --color=always'
alias tf='tail -f -n 1000'

alias cp='cp -r'
alias df="df -h"
alias ip='ip -color'
alias nano='nano -l -T 4'
alias nanol='command nano -T 4'
alias less='less -IN'
alias pwd='pwd -P' # Den absoluten Pfad angeben und keine Symnlinks verwenden
alias rm='rm -R'
alias ssu='sudo --preserve-env=SSH_CLIENT su' # Die Variable speichern für PS1
alias sudo='sudo '                            # https://wiki.archlinux.org/title/Sudo#Passing_aliases
alias time="stopwatch"

[[ -n ${TMUX} ]] && alias help='tmux_help'

[[ -z $(command -v c) ]] && alias c='code .'
[[ -z $(command -v dc) ]] && alias dc='docker-compose'
[[ -z $(command -v dcdu) ]] && alias dcdu='docker-compose down; docker-compose up -d'
[[ -z $(command -v dcdub) ]] && alias dcdub='dcdu --build'
[[ -z $(command -v dps) ]] && alias dps='docker ps --format "table {{.Names}}\t{{.Image}}\t{{.RunningFor}}\t{{.Ports}}"'
[[ -z $(command -v pc) ]] && alias pc='pre-commit run --all-files'
[[ -z $(command -v py) ]] && alias py='python'
[[ -z $(command -v k) ]] && alias k='kubectl'

complete -o default -F __start_kubectl k

# Erkennung, ob die Session im WSL ist. Muss nur ein Mal gemacht werden
is_wsl=false
[[ $(cat /proc/version 2>/dev/null) =~ (M|m)icrosoft ]] && is_wsl=true

# shellcheck disable=2139
[[ ${is_wsl} == true ]] && alias cdh="cd /mnt/c/Users/${USER}" # In das Homeverzeichnis in Windows wechseln
