#!/bin/bash

alias ..="cd .."; alias ...="cd ../.."; alias ....="cd ../../.."
alias .....="cd ../../../.."; alias ......="cd ../../../../.."
alias dc='cd'
alias ls="ls -lh --color=always --time-style='+%H:%M %d.%m.%Y'"; alias l='ls'; alias ll='ls'; alias lll='ls'; alias sl='ls'; alias la="ls -A"
alias rm='rm -R'
alias status='git status'
alias update='sudo apt update && sudo apt list --upgradable'
alias upgradable='sudo apt list --upgradable'
alias mygrep='grep -ins --color=always'
alias nano='nano -l -T 4'
alias less='less -IN'
alias cp='rsync -arh --info=progress2'
alias b='exec $SHELL'
alias pwd='pwd -P' #Den absoluten Pfad angeben und keine Symnlinks verwenden
alias tf='tail -f -n 1000'
alias tmux='tmux -u' #Setzt encoding für ö,ü und ä
alias tmux_help='curl -s "https://gist.githubusercontent.com/henrik/1967800/raw/f580aa23cbc5cbf1bd96dee1c903784c0e32eca2/tmux_cheatsheet.markdown" | "less" -I'

log_auth="/var/log/auth.log"

complete -d cd #Damit werden files ausgeblendet bei der Vervollständigung

LS_COLORS="$(echo "$LS_COLORS" | sed 's/ex=01;32:/ex=32:/g')" #Nur die Farbe von ausführbaren Programmen ersetzen
