#!/bin/bash


########### Farben ###########
GRAU="\[\e[1;30m\]"
DEFAULT="\[\e[0m\]"
GRUEN="\[\e[1;32m\]"
ROT="\[\e[1;31m\]"
PINK="\[\e[35m\]"
CYAN="\[\e[1;36m\]"
##############################


# Erstmal eine Leerzeile für mehr Platz
PS1="\n"

# Linie am Anfang
PS1="$PS1$GRAU\342\224\214\342\224\200"

# Uhrzeit
PS1="$PS1[$DEFAULT\t"

# ]-[
PS1="$PS1$GRAU]-[$DEFAULT"

# Zeichen für Returncode
PS1="$PS1"'`if [ $? = 0 ]; then\
    echo "\[\e[1;32m\]:)";\
else
    echo "\[\e[1;31m\]:(";\
fi`'

# ]-[
PS1="$PS1$GRAU]-[$DEFAULT"

# User und Hostname
PS1="$PS1$GRUEN\u$PINK@$GRUEN\H"

# ]-[
PS1="$PS1$GRAU]-[$DEFAULT"

# Pfad, es wird noch ein "/" angehängt, wenn der aktuelle Pfad != "/" ist
PS1="$PS1$CYAN"'$(pwd)''`[[ $(pwd) != "/" ]] && echo "/"`'"$DEFAULT"

# Git Farbe
PS1="$PS1""$(if [[ $(git status 2>/dev/null) =~ (modified|geändert|ahead|vor|behind|hinter|deleted|gelöscht|neu|new|Unversioniert|Untracked) ]]; then\
    echo "\[\e[31m\]";\
else\
    echo "$GRUEN";\
fi)"

# Git Status
PS1="$PS1"'$(__git_ps1 " (%s)")'

# Klammer zu nach dem Pfad und in die nächste Zeile
PS1="$PS1$GRAU]"$'\n' #\n: https://stackoverflow.com/a/21561763/14638014

# Untere Linie
PS1="$PS1$GRAU\342\224\224\342\224\200\342\224\200> $DEFAULT"
