#!/bin/bash



########### Farben ###########
GRAU="\[\e[1;30m\]"
DEFAULT="\[\e[0m\]"
GRUEN="\[\e[32m\]"
ROT="\[\e[31m\]"
PINK="\[\e[35m\]"
CYAN="\[\e[36m\]"
##############################


# Erstmal eine Leerzeile für mehr Platz
PS1="\n"

# Linie am Anfang
PS1="$PS1$GRAU\342\224\214\342\224\200"

# Uhrzeit
PS1="$PS1[$DEFAULT\t"

# ]-[
PS1="$PS1$GRAU]-[$DEFAULT"

# Zeichen für Returncode
PS1="$PS1"'`if [ $? = 0 ]; then\
    echo "\[\e[32m\]:)";\
else
    echo "\[\e[31m\]:(";\
fi`'

# ]-[
PS1="$PS1$GRAU]-[$DEFAULT"

# User und Hostname
PS1="$PS1$GRUEN\u$PINK@$GRUEN\H"

# ]-[
PS1="$PS1$GRAU]-[$DEFAULT"

# Pfad
PS1="$PS1$CYAN$(pwd)$DEFAULT"

# Git Pfad und Farbe
PS1="$PS1`if [[ $(git status 2>/dev/null) =~ (modified|geändert|ahead|vor|behind|hinter|deleted|gelöscht|neu|new) ]]; then\
    echo "$ROT";\
else\
    echo "$GRUEN";\
fi`\
$(__git_ps1 " (%s)")"

# Klammer zu nach dem Pfad
PS1="$PS1$GRAU]"

# Nächste Zeile
PS1="$PS1\n"

# Untere Linie
PS1="$PS1\342\224\224\342\224\200\342\224\200> $DEFAULT"