#!/bin/bash

check_if_git_repo_exists() { # Prüfen, ob ein GIT Repo gefunden wurde
    if [[ "$(git status 2>&1)" =~ (Kein Git-Repo|not a git repository) ]]; then
        echo -e "\e[31mEs wurde kein GIT Repository gefunden!\e[0m" >&2
        return 1
    fi

    return 0
}

check_for_root_user() { # Returned 1, wenn der aktuell User root ist
    [[ ${UID} == 0 ]] && return 1 || return 0
}

git_base_url() { # Hilfsfunktion, die nur die Core-Url herausfindet
    if ! check_if_git_repo_exists; then return 1; fi

    local repositoryUrl
    repositoryUrl=$(git config --get remote.origin.url | sed 's/\.git//')
    [[ ${repositoryUrl} == *"git@"* ]] && repositoryUrl=$(echo "${repositoryUrl}" | sed 's/:/\//' | sed 's/git@/https:\/\//g')

    [[ -z ${repositoryUrl} ]] && echo -e "\e[31mDie URL konnte nicht bestimmt werden! \e[0m]" && return 1

    echo "${repositoryUrl}"
}

escape_quotes() {
    echo "${@//\"/\\\"}"
}

is_session_ssh() { # Hilfsfunktion, die nur prüft, ob die aktuelle Session eine SSH-Session ist
    local sessionType="lokal"

    if [[ -n "${SSH_CLIENT}" || -n "${SSH_TTY}" || $(ps -o comm= -p ${PPID} 2>/dev/null) == *"sshd"* ]]; then
        sessionType=ssh
    fi

    echo ${sessionType}
}
