#!/bin/bash


########### Farben ###########
GRAU="\[\e[1;30m\]"
DEFAULT="\[\e[0m\]"
GRUEN="\[\e[32m\]"
ROT="\[\e[31m\]"
PINK="\[\e[35m\]"
CYAN="\[\e[1;36m\]"
##############################


# Erstmal eine Leerzeile für mehr Platz
PS1="\n"

# Linie am Anfang
PS1+="${GRAU}\342\224\214\342\224\200"

# Uhrzeit
PS1+="[${DEFAULT}\t"

# ]-[
PS1+="${GRAU}]-[${DEFAULT}"

# Zeichen für Returncode
PS1+='`if [ $? = 0 ]; then\
    echo "\[\e[32m\]:)";\
else
    echo "\[\e[31m\]:(";\
fi`'

# ]-[
PS1+="${GRAU}]-[${DEFAULT}"

# Unterscheidung nach Username
#   - root:  roter  username und "💀"
#   - sonst: grüner username und "@"
[[ $(id -u) -eq 0 ]] && PS1+="${ROT}\u💀" || PS1+="${GRUEN}\u${PINK}@"

# Farbe für den Hostnamen generieren (|| hat nicht funktioniert, deswegen elif)
PS1+='`if [[ -z ${SSH_CLIENT} ]]; then\
    echo "\[\e[32m\]";\
elif [[ ${SSH_CLIENT} == "192.168.178."* && ${SSH_CLIENT} != "192.168.178.30"* && ${SSH_CLIENT} != "192.168.178.28"* && $(hostname) == "openhab" ]]; then\
    echo "\[\e[32m\]";\
else\
    echo "\[\e[31m\]";\
fi`'

# Hostname
PS1+="\H"

# ]-[
PS1+="${GRAU}]-[${DEFAULT}"

# Pfad, es wird noch ein "/" angehängt, wenn der aktuelle Pfad != "/" ist
PS1+="${CYAN}"'$(pwd)''`[[ $(pwd) != "/" ]] && echo "/"`'"${DEFAULT}"

# Git Farbe
PS1+='`if [[ "$(svn info 2>&1)" == *"Wurzelpfad der Arbeitskopie"* ]]; then\
    echo "\[\e[32m\] (svn)";\
elif [[ $(git status 2>/dev/null) =~ (modified|geändert|ahead|vor|behind|hinter|deleted|gelöscht|neu|new|Unversioniert|Untracked) ]]; then\
    echo "\[\e[31m\]";\
elif [[ $(git --no-pager log origin/$(git rev-parse --abbrev-ref HEAD 2>&1)..HEAD --pretty="%cd" 2>&1) =~ (fatal|:) ]]; then\
    echo "\[\e[31m\]";\
else\
    echo "\[\e[32m\]";\
fi`'

# Git Branch, wenn es sich um ein Git Verzeichnis handelt
PS1+=""'$(__git_ps1 " (%s)")'

# Klammer zu nach dem Pfad und in die nächste Zeile
PS1+="${GRAU}]"$'\n' #\n: https://stackoverflow.com/a/21561763/14638014

# Untere Linie
PS1+="${GRAU}\342\224\224\342\224\200\342\224\200> ${DEFAULT}"
