#!/bin/bash

[[ ${USER} == "root" ]]             && return
[[ ${HOSTNAME} =~ (bassi|cronus) ]] && return

text=$(curl http://whatthecommit.com/index.txt 2>/dev/null)
[[ -z ${text} ]] && return

command="echo -e \"${text}\""
[[ -n $(command -v cowthink 2>/dev/null) ]] && command+=" | cowthink"
[[ -n $(command -v lolcat 2>/dev/null) ]]   && command+=" | lolcat"

eval "${command}"