#!/bin/bash

_mdadm_completion() {
	if [[ ${COMP_CWORD} -eq 1 ]]; then
		for item in $(echo -e "--add\n--detail\n--examine" | grep "^${COMP_WORDS[${COMP_CWORD}]}"); do
			COMPREPLY=("${COMPREPLY[@]}" "${item}")
		done
	fi
	if [[ ${COMP_CWORD} -eq 2 ]]; then
		if [[ ${COMP_WORDS[1]} == "--examine" ]]; then
			for item in $(lsblk -o "PATH" | grep -e "sd[a-z][0-9]" | sort -u | grep "^${COMP_WORDS[${COMP_CWORD}]}"); do
				COMPREPLY=("${COMPREPLY[@]}" "${item}")
			done
		elif [[ ${COMP_WORDS[1]} == "--add" || ${COMP_WORDS[1]} == "--detail" ]]; then
			for item in $(lsblk -o "PATH,TYPE" | grep raid | sort -u | cut -d " " -f1 | grep "^${COMP_WORDS[${COMP_CWORD}]}"); do
				COMPREPLY=("${COMPREPLY[@]}" "${item}")
			done
		fi
	fi
	if [[ ${COMP_CWORD} -eq 3 ]]; then
		for item in $(lsblk -o "PATH" | grep -e "sd[a-z][0-9]" | sort -u | grep "^${COMP_WORDS[${COMP_CWORD}]}"); do
			COMPREPLY=("${COMPREPLY[@]}" "${item}")
		done
	fi
}

complete -F _mdadm_completion mdadm

checkout_homeassistant_pr() {
	if [[ ${UID} != 0 ]]; then
		echo -e "\e[31mThis script must be run as root.\e[0m"
		return 1
	fi
	if [[ ${#} -ne 2 ]]; then
		echo -e "\e[31mUsage: checkout_homeassistant_pr <domain> <PR number>\e[0m"
		return 1
	fi

	cd /home/felix/server/HomeAssistant/data/homeassistant/config/ || return 1
	curl -o- -L https://gist.githubusercontent.com/bdraco/43f8043cb04b9838383fd71353e99b18/raw/core_integration_pr | bash /dev/stdin -d "${1}" -p "${2}"
}

cleanup_homeassistant_pr() {
	if [[ ${UID} != 0 ]]; then
		echo -e "\e[31mThis script must be run as root.\e[0m"
		return 1
	fi

	rm -rf "/home/felix/server/HomeAssistant/data/homeassistant/config/custom_components/${1}"
}