#!/bin/bash

alias ..="cd .."
alias ,,=".."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias ls="ls -lh --color=always --time-style='+%H:%M %d.%m.%Y'"
alias l='ls'
alias ll='ls'
alias lll='ls'
alias sl='ls'
alias la="ls -A"

alias upgradable='apt list --upgradable'
alias update='sudo apt update && apt list --upgradable'

alias b='exec ${SHELL} -l' # -l ensures that the bashrc is loaded
alias cp='cp -r'
alias df="df -h --exclude-type=overlay"
alias ip='ip -color'
alias mygrep='grep -ins --color=always'
alias nano='nano -l -T 4'
alias nanol='command nano -T 4'
alias lsblk='lsblk -e 7 -o NAME,TYPE,FSUSED,FSAVAIL,SIZE,FSUSE%,MOUNTPOINT'
alias less='less -IN'
alias pwd='pwd -P' # Den absoluten Pfad angeben und keine Symnlinks verwenden
alias rm='rm -I -v'
alias ssu='sudo --preserve-env=SSH_CLIENT su' # Die Variable speichern für PS1
alias sudo='sudo '                            # https://wiki.archlinux.org/title/Sudo#Passing_aliases
alias tf='tail -f -n 1000'

[[ -n ${TMUX} ]] && alias help='tmux_help'

alias c='code .'
alias d='docker' && complete -F _docker d
alias dc='docker compose'
alias dcdu='dc up -d --force-recreate'
alias dcdub='dc pull; dc up -d --build --force-recreate'
alias dcl='dc logs -f'
alias dps='docker ps --format "table {{.Names}}\t{{.Image}}\t{{.RunningFor}}\t{{.Ports}}"'
alias lg='lazygit'
alias pc='pre-commit run --all-files'
alias py='python'
alias k='kubectl' && complete -o default -F __start_kubectl k
