#!/bin/bash

alias ..="cd .."
alias ,,=".."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias ls="ls -lh --color=always --time-style='+%H:%M %d.%m.%Y'"
alias l='ls'
alias ll='ls'
alias lll='ls'
alias sl='ls'
alias la="ls -A"

alias b='exec ${SHELL} -l' # -l ensures that the bashrc is loaded
alias cp='cp -r'
alias df="df -h --exclude-type=overlay --exclude-type=tmpfs"
alias ip='ip -color'
alias mygrep='grep -ins --color=always'
alias lsblk='lsblk -e 7 -o NAME,TYPE,FSUSED,FSAVAIL,SIZE,FSUSE%,MOUNTPOINT'
alias less='less -IN'
alias pwd='pwd -P' # Show the absolute path, not the symlink
alias rm='rm -I -v'
alias sudo='sudo --preserve-env=SSH_CLIENT ' # Save SSH state and https://wiki.archlinux.org/title/Sudo#Passing_aliases
alias tf='tail -f -n 1000'

alias c='code .'
alias d='docker' && complete -F _docker d
alias dc='docker compose'
alias dcdu='dc up -d --force-recreate'
alias dcdub='dc up --pull always -d --build --force-recreate'
alias dcl='dc logs -f'
alias dps='docker ps --format "table {{.Names}}\t{{.Image}}\t{{.RunningFor}}\t{{.Ports}}" | awk '\''NR==1{print; next} {print | "sort"}'\'''
alias lg='lazygit'
alias pc='pre-commit run --all-files'
alias k='kubectl' && complete -o default -F __start_kubectl k
