#!/bin/bash

complete -d cd                                                     # Damit werden files ausgeblendet bei der Vervollständigung
shopt -s cdspell                                                   # Korrigiert kleine Typos bei Pfaden nach dem Abschicken
[[ $(echo "${BASH_VERSION}" | cut -c1) -ge 4 ]] && shopt -s autocd # In dir wechseln ohne cd (erst ab BASH v.4 verfügbar)

bind 'set show-all-if-ambiguous on'  # Spart ein mal <TAB> drücken bevor die Autocompletion angezeigt wird
bind 'set completion-ignore-case on' # Ignoriert Groß- und Kleinschreibung bei der Autocompletion
bind 'set completion-map-case on'    # Ähnlich wie completion-ignore-case, setzt "-" und "_" als äquivalent

bind '"\e[A": history-search-backward' # Sucht history mit dem schon bestehenden String anstatt ihn zu verwerfen
bind '"\e[B": history-search-forward'  # Siehe https://stackoverflow.com/a/42299929

LS_COLORS=${LS_COLORS//ex=01;32:/ex=32:} # Die Farbe von ausführbaren Programmen ersetzen von grau zu grün

export HISTCONTROL=ignoreboth              # Schreibe nicht in die history was doppelt ist oder in HISTIGNORE steht
export HISTIGNORE="clear"                  # Kommandos, die nicht in die History aufgenommen werden
export HISTTIMEFORMAT="%d.%m. %H:%M:%S - " # Format der History anpassen
export HISTSIZE=10000                      # Anzahl der Kommandos, die im Memory gespeichert bleiben
export HISTFILESIZE=30000                  # Anzahl der Kommandos, die in .bash_history gespeichert bleiben
export PROMPT_COMMAND='history -a'         # Synchronisert alle Bashhistories von mehreren Terminals https://askubuntu.com/a/80380
shopt -s histappend                        # Kommandos werden an die History angehängt statt die History zu überschreiben
shopt -s checkwinsize                      # Nach jedem Kommando die Größe des Fensters checken

export LANG=de_DE.UTF-8 2>/dev/null
export LANGUAGE=de_DE.UTF-8 2>/dev/null
export LC_ALL=de_DE.UTF-8 2>/dev/null
export VIRTUAL_ENV_DISABLE_PROMPT=1 # Auschalten der automatischen Anspassung von $PS1 durch venv
export EDITOR="nano"

export COMPOSE_BAKE=true
