#!/bin/bash

# In wsl die den credential manager von windows benutzen, da er um EINIGES schneller ist
# https://stackoverflow.com/a/47350274
# Zusätzlich keinen pager verwenden
# shellcheck disable=2154
if [[ ${is_wsl} == true ]]; then
    git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
else
    git config --global --unset credential.helper
fi
alias git='git --no-pager'

check_if_git_repo_exists() { # Prüfen, ob ein GIT Repo gefunden wurde
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        return 0
    fi

    echo -e "\e[31mEs wurde kein GIT Repository gefunden!\e[0m" >&2
    return 0
}
