#!/bin/bash

########### Farben ###########
GRAU="\[\e[1;30m\]"
DEFAULT="\[\e[0m\]"
GRUEN="\[\e[32m\]"
ROT="\[\e[31m\]"
PINK="\[\e[35m\]"
CYAN="\[\e[1;36m\]"
##############################

# Berechnung dafür wie lang das Kommando gedauert hat
function timer_start {
	timer=${timer:-${SECONDS}}
}

function timer_stop {
	timer_show=""
	delta=$((SECONDS - timer))
	[[ ${delta} -lt 10 ]] && {
		unset timer
		return
	}

	((stunden = (delta % 86400) / 3600))
	((minuten = (delta % 3600) / 60))
	((sekunden = delta % 60))

	[[ ${stunden} != 0 ]] && timer_show+=$(printf "%dh " ${stunden})
	[[ ${minuten} != 0 ]] && timer_show+=$(printf "%dm " ${minuten})
	timer_show+=$(printf "%ds" ${sekunden})

	unset timer
}

trap 'timer_start' DEBUG # FIXME: Statt aufrufen beim Bauen der Kommandozeile lieber beim Kommandostart

# Erstmal eine Leerzeile für mehr Platz
PS1="\n"

# Linie am Anfang
PS1+="${GRAU}\342\224\214\342\224\200"

# Uhrzeit
PS1+="[${DEFAULT}\t"

# ]-[
PS1+="${GRAU}]-[${DEFAULT}"

# Zeichen für Returncode
PS1+='`[[ $? = 0 ]] && echo "\[\e[32m\]:)" || echo "\[\e[31m\]:("`'

# ]-[
PS1+="${GRAU}]-[${DEFAULT}"

# Unterscheidung nach Username
#   - root:  roter  username und "💀"
#   - sonst: grüner username und "@"
[[ $(id -u) -eq 0 ]] && PS1+="${ROT}\u💀" || PS1+="${GRUEN}\u${PINK}@"

# Farbe für den Hostnamen generieren. Unterscheidung nach SSH Session
#   - SSH-Session:    Hostname rot
#   - Lokale Session: Hostname grün
PS1+='`[[ -z ${SSH_CLIENT} ]] && echo "\[\e[32m\]" || echo "\[\e[31m\]"`'

# Hostname
PS1+="$(hostname -s)"

# WSL Ausgabe
#    - bei WSL: "]-[WSL" Einschub
#    - sonst:   Nichts
# shellcheck disable=2154
PS1+='`[[ ${is_wsl} == true ]] && echo "\[\e[1;30m\]]-[\[\e[0;32m\]WSL"`'

# Python Venv Ausgabe
#    - bei Venv: "]-[Venv" Einschub
#    - sonst:    Nichts
PS1+='`[[ -n ${VIRTUAL_ENV} ]] && echo "\[\e[1;30m\]]-[\[\e[0;32m\]Venv"`'

# ]-[
PS1+="${GRAU}]-[${DEFAULT}"

# Pfad, es wird noch ein "/" angehängt, wenn der aktuelle Pfad != "/" ist
PS1+="${CYAN}"'$(pwd)''`[[ $(pwd) != "/" ]] && echo "/"`'"${DEFAULT}"

# Git Farbe
PS1+='`
if [[ $(git status 2>/dev/null) =~ (ahead| vor |behind|hinter|deleted|gelöscht|neu|new|Unversioniert|Untracked|umbenannt|renamed) ]]; then
    echo "\[\e[31m\]"
elif [[ $(git status 2>/dev/null) =~ (modified|geändert) ]]; then
    echo "\[\e[0;33m\]"
elif [[ -z $(git remote -v 2>&1) ]]; then
	echo "\[\e[32m\]"
elif [[ $(git --no-pager log origin/$(git rev-parse --abbrev-ref HEAD 2>&1)..HEAD --pretty="%cd" 2>&1) =~ (fatal|:) ]]; then
    echo "\[\e[31m\]"
else
    echo "\[\e[32m\]"
fi`'

# Git Branch, wenn es sich um ein Git Verzeichnis handelt
PS1+='`__git_ps1 " (%s)"`'

# Wenn das Kommando länger als 10 Sekunden gedauert hat wird die Dauer ausgegeben
PROMPT_COMMAND=timer_stop
PS1+='`[[ -n ${timer_show} ]] && echo "\[\e[1;30m\]]-[\[\e[0m\]${timer_show}"`'

# Klammer zu nach dem Pfad und in die nächste Zeile
PS1+="${GRAU}]"$'\n' # \n: https://stackoverflow.com/a/21561763/14638014

# Untere Linie
PS1+="${GRAU}\342\224\224\342\224\200\342\224\200> ${DEFAULT}"
