#!/bin/bash

alias ls="ls -lh --color=always -D'%H:%M %d.%m.%Y'"
export PATH=${HOME}/Library/Python/3.13/bin:/usr/local/bin:${PATH}
export LIBRARY_PATH=/usr/local/lib
export C_INCLUDE_PATH=/usr/local/include
export HOMEBREW_NO_ENV_HINTS=1
# shellcheck disable=1091
[[ -f /usr/local/etc/bash_completion ]] && . /usr/local/etc/bash_completion
