#!/bin/bash

battery(){
    echo -ne "Status:\e[96;1m"
    acpi | grep "Battery 0" | cut -d ":" -f2- | sed 's/, rate information unavailable//'
    echo -ne "\e[0m"
}

build(){
    echo -e "\e[1;36mPaket wird gebaut\e[0m"
    local start_time=`date +%s`
    dpkg-buildpackage -us -uc
    [[ $? != "0" ]] && return 1
    mv ../abm-*.deb .
    find ../abm-* -maxdepth 1 -type f -exec rm {} \;
    debian/rules clean >/dev/null
    local end_time=`date +%s`
    local deb_package=$(ls -1t *.deb | head -1 | egrep -o "abm-.{1,}deb")
    sudo dpkg -i $deb_package
    echo -e "\n\n\e[1;36mDas Bauen des Pakets hat $(date -u --date @$(($end_time - $start_time)) +%M:%S) gedauert"
    echo -e "Soll das Paket hochgeladen werden?\e[0m"
    read -e answer
    if [[ $answer =~ ^[YyJj]$ ]]; then
       upload "$deb_package"
    fi
}

upload(){
    if [[ -z ${1} ]]; then
        sftp abm@packages.abm-local.de:/incoming
    else
        sftp abm@packages.abm-local.de:/incoming <<EOF
put $1
exit
EOF
    fi
}