#!/bin/bash

battery(){
    echo -ne "Status:\e[96;1m"
    acpi | grep "Battery 0" | cut -d ":" -f2- | sed 's/, rate information unavailable//'
    echo -ne "\e[0m"
}


baslog(){
    cd "/var/log/bas/$(date +'%d.%m.%Y')" || echo -e "\e[31mEs wurde kein aktueller Log gefunden\e[0m"; return 1
    local logfile="$(command ls -1t | head -n 1)"
    echo -e "\e[96;1m"; center "Logfile: ${logfile}"; echo -e "\e[0m\n"
    tail -f -n 1000 "${logfile}"
    cd - >/dev/null
}


build(){
    echo -e "\e[1;36mPaket wird gebaut\e[0m"

    local startTime=$(date +%s)

    dpkg-buildpackage -us -uc
    [[ $? != "0" ]] && return 1

    mv ../*.deb .
    rm ../*.{buildinfo,changes,dsc,tar.gz}
    debian/rules clean >/dev/null

    local endTime=$(date +%s)

    local debianPackageName=$("ls" -1t *.deb | head -1)
    sudo dpkg -i ${debianPackageName}

    echo -e "\n\n\e[1;36mDas Bauen des Pakets hat $(date -u --date @$((${endTime} - ${startTime})) +%M:%S) gedauert"

    echo -e "Soll das Paket hochgeladen werden?\e[0m"
    read -e -n1 answer
    if [[ ${answer} =~ ^[YyJj]$ ]]; then
       upload "${debianPackageName}"
    fi
}


upload(){
    if [[ -z ${1} ]]; then
        sftp abm@packages.abm-local.de:/incoming
    else
        sftp abm@packages.abm-local.de:/incoming <<EOF
put $1
exit
EOF
    fi
}