#!/bin/bash


# _diff()
# {
#     _init_completion || return

#     local IFS=$'\n' i j k

#     # echo $filenames

#     compopt -o filenames

#     # Use standard dir completion if no CDPATH or parameter starts with /,
#     # ./ or ../
#     # if [[ -z "${CDPATH:-}" || "$cur" == ?(.)?(.)/* ]]; then
#     #     # echo "test4"
#         _filedir -d
#     #     COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="diff"
#     #     COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="pull"
#     #     return
#     # fi
#     local ausgewaehlte_server
#     for wert in ${#COMPREPLY[@]}; do
#         ausgewaehlte_server+=" ""$wert"
#     done
#     local anfang="${COMP_WORDS[$COMP_CWORD]}"
#     for kdsys in $( echo $ausgewaehlte_server | sed 's/ /\n/g' | grep -P "^$anfang" ); do
#         COMPREPLY=("${COMPREPLY[@]}" "$kdsys")
#     done
#     return

#     # COMPREPLY="$COMPREPLY"" diff pull"

#     # COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="diff"
#     # COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="pull"
#     echo "test0"

#     echo $COMPREPLY
#     echo "test1"
#     COMPREPLY[k++]="diff"
#     COMPREPLY[k++]="pull"
#     echo "test2"

#     return
# }
# # complete -F _filedir diff
# complete -F _diff diff
# # complete -F _mine diff


# # _filedir()
# # {
# #     local IFS=$'\n'

# #     _tilde "$cur" || return

# #     local -a toks
# #     local x reset

# #     reset=$(shopt -po noglob); set -o noglob
# #     toks=( $( compgen -d -- "$cur" ) )
# #     eval $reset



# #     if [[ ${#toks[@]} -ne 0 ]]; then
# #         # 2>/dev/null for direct invocation, e.g. in the _filedir unit test
# #         compopt -o filenames 2>/dev/null
# #         COMPREPLY+=( "${toks[@]}" )
# #         # echo $COMPREPLY[0]
# #         # echo $COMPREPLY[1]
# #         # echo $COMPREPLY[2]



# #         # COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="diff"
# #         # COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="pull"
# #     fi
# # } # _filedir()


# _mine(){
#     local IFS=$'\n'
#     echo $cur
#     toks=( $( complete -f -- "$cur" ) )
#     echo $toks
#     COMPREPLY+=( "${toks[@]}" )
#         COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="diff"
#     COMPREPLY[$((${#COMPREPLY[@]} + 1 ))]="pull"
# }


# #!/bin/bash

# mkdir -p {my,other}/path/to/{a,b,c}

function _cd() {
    COMPREPLY=( diff pull );
}
complete -o nospace -F _cd diff

function _cd2() {
    local cur opts;
    cur="${COMP_WORDS[COMP_CWORD]}";
    _cd;
    opts="${COMPREPLY[@]}";        # here we combine options
    COMPREPLY=($(compgen -W "${opts}" -- ${cur})); # here is the secret sauce
}

complete -f diff
complete -F _cd2 diff

complete -p diff