#!/bin/bash

export PATH=/usr/local/Cellar:${HOME}/Library/Python/3.13/bin:/usr/local/bin:${PATH}
export LIBRARY_PATH=/usr/local/lib
export C_INCLUDE_PATH=/usr/local/include
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_AUTO_UPDATE=1
