#!/bin/bash

[[ "${OSTYPE}" != darwin* ]] && return

alias ls="ls -lh --color=always -D'%H:%M %d.%m.%Y'"

export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_AUTO_UPDATE=1
export BASH_SILENCE_DEPRECATION_WARNING=1
