#!/bin/bash

# shellcheck disable=2139

# We have to check whether pip is an executable since pip is shadowed by a shell function
[[ ! -x "$(command -v pip)" ]] && alias pip="python3 -m pip"

latest_python=$(
    compgen -c python \
    | grep -E '^python3\.[0-9]+$' \
    | sort -V \
    | tail -n1
)
alias py="${latest_python}"
alias python="${latest_python}"
alias python3="${latest_python}"
